title: "[Kyrell Green] | Portfolio"
description: "[Aspiring Cyber Security Analyst]"
theme: jekyll-theme-hacker
show_downloads: false

# Branding
branding:
  logo: "/assets/images/dae_logo_color.jpeg"
  logo_alt: "dae logo"

# Personal Details
personal_details:
  full_name: "[Kyrell Green]"
  graduation_date: "[December 2026]"
  profile_photo: "/assets/images/profile_pic.jpeg"

# About Me
about_me:
  bio_summary: "[My name is Kyrell Green. Im interested in getting into the tech industry after shifting careers. I aquired technological skills through hobbies, research trial and error.
                  aspire to complete the DAE 6 month program, get certified and step forward into a career that I actually enjoy. ]"
  interests_values: "[I'm always interested in learning, reading tech TLDR's, tinkering with devices and systems, finding out what makes things tic.]"

# Career Aspirations
career_aspirations:
  preferred_roles: "[Cyber Security Analyst, I.T. Helpdesk]"
  ideal_environment: "[Hybrid/Remote]"
  ideal_job: "[Security SOC Analyst]"
  ideal_team: "[My ideal team would be like minded people, passionate about not only what they do but why they do it."
  future_goals: "[I hope I can make a positive impact doing what I enjoy.]"

# Contact Information
contact_info:
  email: "[Rellg66@gmail.com]"
  linkedin: "[www.linkedin.com/in/
              kai-green-884254303]"
  github: "[https://github.com/Kai0sama28/DAE-6-Month-Project-Files]"

# Projects
projects:
  - name: "[PROJECT 1 NAME]"
    image: "/assets/images/project-placeholder.svg"
    description: "[PROJECT 1 DESCRIPTION]"
    repo_url: "[PROJECT 1 GITHUB URL]"
    demo_url: "[PROJECT 1 LIVE URL, IF APPLICABLE]"
    contribution: "[YOUR CONTRIBUTION]"
    tools: "[TOOLS OR TECHNOLOGIES]"
  - name: "[PROJECT 2 NAME]"
    image: "/assets/images/project-placeholder.svg"
    description: "[PROJECT 2 DESCRIPTION]"
    repo_url: "[PROJECT 2 GITHUB URL]"
    demo_url: "[PROJECT 2 LIVE URL, IF APPLICABLE]"
    contribution: "[YOUR CONTRIBUTION]"
    tools: "[TOOLS OR TECHNOLOGIES]"
  - name: "[PROJECT 3 NAME]"
    image: "/assets/images/project-placeholder.svg"
    description: "[PROJECT 3 DESCRIPTION]"
    repo_url: "[PROJECT 3 GITHUB URL]"
    demo_url: "[PROJECT 3 LIVE URL, IF APPLICABLE]"
    contribution: "[YOUR CONTRIBUTION]"
    tools: "[TOOLS OR TECHNOLOGIES]"

# Navigation Links
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about.html"
  - title: "Projects"
    url: "/projects.html"
  - title: "Contact"
    url: "/contact.html"
